print("Today you will help tell a story")
name = input("what is your name?")
print(f"Hello {name} and welcome to a choose your own story")
print("")
print("")
animal = input("please pick a animal:")
print("-----------------````~~~~~~~~~~~~~~~~~~~~")
location = input("Now pick a location:")
print("~~~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~+~~~~+~")
car = input("Now pick a car:")
print("//////////////////////////////////////////")
hat = input("now pick a type of hat:")
print("***********************************************")
print("^^")
print(f"one day a {animal} drove into {location} while driving a {car} he was wearing a {hat}")
print("")
animal = input("now pick a animal:")
print("")
noun = input("now choose a noun:")
print(f"one day a {animal} rode on a {noun} and reached the i store")