print("Today you will help tell a story")
name = input("what is your name?")
print("Hello {name}")
print("")
print("")
movie character = input("please pick a movie character:")
print("-----------------````~~~~~~~~~~~~~~~~~~~~")
location = input("Now pick a location:")
print("~~~~~~~~~~~~~~~~~~~+~~~~~~~~~~~~~~~~+~~~~+~")
car = input("Now pick a car:")
print("//////////////////////////////////////////")
hat = input("now pick a type of hat")
print("***********************************************")
print("^^")
