print("Why did the cow become an astronaut")
input("")
print("To go to the moon!!")
print("Why dont oysters donate to charity")
input("")
print("Because there shellfish!!")
print("What do you call a fly without wings")
input("")
print("A walk!!")
print("Whats the action like at a circus")
input("")
print("in-tents!!")